# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e019bc841d680d664a4a6211e6e2ace32097d65e0fbf7e0b20c96edbf72622de98d0f6291d545e6e54572c546ab00cac957dfb55d71c98fba412a92ddb6fcdc4

test:
  secret_key_base: c8af4bcfef0f151fd02173fdb28e577be25d8213f3f2ddae6ada1ed6b1858452cd7c5bade9d4e759ab726560749a435f3b933a81f2b4f15d0c1f8da88dfe6c5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
